find_path(SDL2_INCLUDE_DIR
	NAMES
		SDL.h
	PATHS
		${CMAKE_CURRENT_LIST_DIR}/lib/SDL2-2.0.10/include
)

find_library(SDL2_LIBRARY
	NAMES
		SDL2
	PATHS
		${CMAKE_CURRENT_LIST_DIR}/lib/SDL2-2.0.10/lib/x64
)

find_library(SDL2_LIBRARY_MAIN
	NAMES
		SDL2main
	PATHS
		${CMAKE_CURRENT_LIST_DIR}/lib/SDL2-2.0.10/lib/x64
)

set(SDL2_LIBRARIES ${SDL2_LIBRARY} ${SDL2_LIBRARY_MAIN})
